config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'
  get 'relationships/unfollow_user'
  get 'profiles/show'
  devise_for :users , controllers: { registrations: 'registrations' }
  resources :posts do
    resources :comments
  end
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'profiles/index', as: :profiles
  # get ':index', to: 'profiles#index', as: :all_profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  # root to: 'profiles#index'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  # before_action :owned_profile, only: [:edit, :update]

  def index
    # @search = User.all.ransack(params[:q])
    # @profiles = @search.result
    # query = User.all
    # @profiles = User.find_by("user_name LIKE :query", query: "%#{query}%")
    @profiles = User.all
  end

  def show
    @user = User.find_by(user_name: params[:user_name])
    @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end

  def edit
    @user = User.find_by(user_name: params[:user_name])
  end

  def update
    @user = User.find_by(user_name: params[:user_name])
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private

  # def owned_profile
  #   @user = User.find_by(user_name: params[:user_name])
  #   unless current_user == @user
  #     flash[:alert] = "That profile doesn't belong to you!"
  #     redirect_to root_path
  #   end
  # end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Change your profile image:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/follow_user.js.erb
$('#follow-button').attr('class', 'btn unfollow-button')
                   .text('Following')
                   .attr('href', "/<%= @user.user_name %>/unfollow_user")
                   .attr('id', 'unfollow-button');

app/views/profiles/index.html.erb
<h1 align="center"> All Profiles </h1>
<div align="center">
  <% @profiles.each do |profile| %>
    <%= link_to profile.user_name, profile_path(profile.user_name), class: "align center btn btn-primary" %>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= profile_avatar_select(@user) %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name">
          <%= @user.user_name %>
        </h3>
        <span>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'btn edit-button' %>
          <% else %>
            <% if current_user_is_following(current_user.id, @user.id) %>
              <%= link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
            <% else %>
              <%= link_to 'Following', follow_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
            <% end %>
          <% end %>
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics">
        <p>
          <%= pluralize @user.posts.count, 'post' %>
        </p>
        <p>
          <div id="element1" class="btn btn-default show-modal1">Following: <%= current_user.following.count %></div>
        </p>
        <p>
          <div id="element2" class="btn btn-default show-modal2">Follower: <%= current_user.followers.count %></div>
        </p>
      </div>
    </div>
  </div>
</div>
<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>


<div id="testmodal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Following Profiles</h4>
      </div>
      <div class="modal-body">
        Following:
        <% current_user.following.each do |following| %>
          <%= following.user_name %></br>
        <% end %>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

<div id="testmodal1" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Followers Profiles</h4>
      </div>
      <div class="modal-body">
        Followers:
        <% current_user.followers.each do |followers| %>
          <%= followers.user_name %>
        <% end %>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    var show_btn1=$('.show-modal1');
    var show_btn2=$('.show-modal2');
    //$("#testmodal").modal('show');
    
    show_btn1.click(function(){
      $("#testmodal").modal('show');
    })
    show_btn2.click(function(){
      $("#testmodal1").modal('show');
    })
  });

  $(function() {
    $('#element1, #element2').on('click', function( e ) {
      Custombox.open({
        target: '#testmodal1',
        effect: 'fadein'
      });
      e.preventDefault();
    });
  });
</script>

app/views/profiles/unfollow_user.js.erb
$('#unfollow-button').text('Follow')
                     .attr('class', 'btn follow-button')
                     .attr('href', "/<%= @user.user_name %>/follow_user")
                     .attr('id', 'follow-button');