config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'
  get 'relationships/unfollow_user'
  get 'profiles/show'
  devise_for :users , controllers: { registrations: 'registrations' }
  resources :posts do
    resources :comments
  end
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'profiles/index', as: :profiles
  # get ':index', to: 'profiles#index', as: :all_profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  # root to: 'profiles#index'
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  validates :image, presence: true

  # has_attached_file :image, styles: { :medium => "640x" }
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  has_many :comments, dependent: :destroy

  scope :of_followed_users, -> (following_users) { where user_id: following_users }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  # before_action :owned_post, only: [:edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    # @posts = Post.all.order('created_at DESC').page params[:page]
    posts = current_user.posts.order('created_at DESC')
    @posts = Post.of_followed_users(current_user.following.pluck(:id).push(current_user.id)).order('created_at DESC').page params[:page]
  end
  
  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end  

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed.  Please check the form."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end


  private

  def post_params
    params.require(:post).permit(:image, :caption, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
  # def owned_post
  #   unless current_user == @post.user
  #     flash[:alert] = "That post doesn't belong to you!"
  #     redirect_to root_path
  #   end
  # end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%#= image_tag 'placeholder.jpg', id: 'image-preview', class: 'img-responsive' %>
        <%= form_image_select(@post) %>
        <%= simple_form_for @post, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4>Upload an image (this is required):</h4>
              <%= f.input :image, label: false, input_html: { onChange: 'loadFile(event)' } %>
            </div>
            <div class="form-group text-center">
              <%= f.input :caption, label: false, placeholder: 'Add your caption' %>
            </div>
            <div class="form-group text-center">
              <%= f.button :submit, class: 'btn-success btn-block' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
      </div>
    </div>
    <div class="time-ago">
      <%= time_ago_in_words post.created_at %>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="comments" id="comments_<%= post.id %>">
      <% if post.comments.any? %>
        <div class="paginator" id="#comments-paginator-<%= post.id %>">
          <% unless post.comments.count <= 4 %>
            <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"} %>
          <% end %>
        </div>
        <%= render post.comments.last(4), post: post %>
      <% end %>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <span class="glyphicon glyphicon-heart-empty"></span>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.new] , remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post_dashboard.html.erb
<div id="posts">
  <%#= render 'posts' %>
</div>
<div class="text-center" id="paginator">
  <%#= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
</div>

app/views/posts/_post_dashboard.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/browse.html.erb
<%= render 'post_dashboard', posts: @posts %>

app/views/posts/edit.html.erb
<!-- <div class="text-center">
  <%#= image_tag @post.image.url(:medium) %>
</div> -->

<%= render 'form' %>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<h1 align="center"> Geogram of <%= current_user.user_name %>( Following: <%= current_user.following.count %>, Follower: <%= current_user.followers.count %>) </h1>
<div align="left">
  Followers:
  <% current_user.followers.each do |followers| %>
    <%= followers.user_name %>
  <% end %>
</div>
<div align="right">
  Following:
  <% current_user.following.each do |following| %>
    <%= following.user_name %>
  <% end %>
</div>
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>
<%= paginate @posts %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<!-- <div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
        Ben Walker
      </div>
    </div>
    <div class="image center-block">
      <%#= image_tag @post.image.url(:medium) %>
    </div>
    <p class="caption">
      <%= @post.caption %>
    </p>
    <div class="text-center edit-links">
      <%# if @post.user.id == current_user.id %>
        <%#= link_to "Cancel", posts_path %>
        |
        <%#= link_to "Edit Post", edit_post_path(@post) %>
      <%# else %>
       <%#= link_to "Cancel", posts_path %>
      <%# end %>
    </div>
  </div>
</div> -->
<%= render 'post', post: @post %>
<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
    |
    <%= link_to "Edit Post", edit_post_path(@post) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
  </div>
<% end %>